#!/usr/bin/env python3

#Exercício bônus 2

dna1 = 'AGCAC----CCTCCCACCTCATCCCACCCTTCTGATCTCAATCCAACG-TCG-----------CATCTCCACCGTCTCGC-GGATCGACCCAG----CGAAGTCCCTC--CCGCC--CCCAAAGTCCC--------CCAAATCTTGCAGT-TCCCTCCTAAATCCTCCCCA----TATAAACC-------AA---CCCCC-CGCCCTCAGATCCCTAATCCCA--------TCGCAAGC-ATCAGACTCCCTC---C-AAAGCAG---GCA--------------GCAGCTCCTC-TTCTTCCTAATCACACTATCTCGGAGAG-------------------------GAGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGCCGCACCCTCTACGGCTTCGGAGGCTAGA---TTTGT--------GTGGTGAAGCAA----CTTCCTCGT---TTGCTCTGTGATCTGTGC---TGTCGTAGATGAGATTTAC-TGATTT--------------GGCGTGCGCCGGTTGTATTCTGTCATGGGGTTCA-----GTGGGCTGTGTAATACCTTGCTCTGTACTTCTGTTCAATGCAATCACTT-CTATTCTGAA'
dna2 = 'TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAATCGATGCTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGTCTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTATTACTATATAAAGTACTGCTGCGAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCTTTGGCGGCTGAGTGTTTTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAGGTTCGGTGCCCCT-TTCA--GC-ATTACTTAGTGGTTAAAA'

diferenças = 0
for i in range(len(dna1)): 
    if dna1[i] != dna2[i]:
        diferenças += 1 #primeiro, será comparada cada caractere de ambas as sequências e armazenada o número de caracteres contrastantes em 'diferenças'
iguais = len(dna1) - diferenças #o número de caracteres iguais então é armazenado em "iguais"
identidade = (iguais/len(dna1))*100 #porcentagem calculada da identidade
print("caracteres diferentes: ", diferenças, "caracteres iguais: ", iguais, "identidade: ", identidade,"%")